language: node_js
node_js:
- '4'
before_install:
- npm install -g grunt-cli
script:
  - npm run build
  - npm test
deploy:
  provider: releases
  api_key:
    secure: Zg+GCHwwrBFLIpHD/NY6l+/vMIqdg2OxcwZoYwJzGG4OnOwjNy/xCV5OuLrqAYRUfrexErmIubvckyc29SByv/DqEKIUXAIHaQeqJs/Z6Qq28HpG/s0ExLKwvjogKtY1wei4YCzZLQf8Faae3c7PWaKXnhKdQpvwlhgA8xvw/X0=
  file:
    - "dist/bit-imports.min.js"
    - "dist/bit-imports.min.js.map"
  skip_cleanup: true
  on:
    repo: MiguelCastillo/bit-imports
    tags: true
    all_branches: true
